# Generated by Django 4.2.3 on 2025-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nama Proyek (Judul Besar)"
                    ),
                ),
                (
                    "url_peta",
                    models.URLField(
                        help_text="Masukkan URL yang di-host (contoh: https://nabilulilalbab.github.io/petapapua/)",
                        max_length=500,
                        verbose_name="URL Peta QGIS2Web (iFrame Source)",
                    ),
                ),
                (
                    "data_csv",
                    models.FileField(
                        help_text="Upload file data statistik (seperti test2113.csv) untuk analisis korelasi.",
                        upload_to="qgis_data/",
                        verbose_name="Upload File Data CSV",
                    ),
                ),
                (
                    "tahun_mulai",
                    models.IntegerField(default=2022, verbose_name="Tahun Mulai Data"),
                ),
                (
                    "tahun_akhir",
                    models.IntegerField(default=2024, verbose_name="Tahun Akhir Data"),
                ),
                (
                    "lingkup_geografi",
                    models.CharField(
                        default="Kabupaten/Kota di Provinsi Papua",
                        max_length=255,
                        verbose_name="Lingkup Geografi",
                    ),
                ),
                (
                    "sumber_data",
                    models.CharField(
                        default="Survei Sosial Ekonomi Nasional (Susenas)",
                        max_length=255,
                        verbose_name="Sumber Data Utama",
                    ),
                ),
                (
                    "platform_gis",
                    models.CharField(
                        default="QGIS & Leaflet",
                        max_length=100,
                        verbose_name="Platform GIS",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Konfigurasi Halaman Utama",
                "verbose_name_plural": "Konfigurasi Halaman Utama",
            },
        ),
    ]
