# Generated by Django 5.2.8 on 2025-11-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearlyMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tahun",
                    models.IntegerField(
                        help_text="Tahun data peta (contoh: 2022, 2023, 2024)",
                        unique=True,
                        verbose_name="Tahun",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        help_text="Contoh: Peta Inflasi Papua 2024",
                        max_length=200,
                        verbose_name="Judul Peta Tahun Ini",
                    ),
                ),
                (
                    "url_peta",
                    models.URLField(
                        help_text="URL peta spesifik untuk tahun ini",
                        max_length=500,
                        verbose_name="URL Peta QGIS2Web untuk Tahun Ini",
                    ),
                ),
                (
                    "data_csv",
                    models.FileField(
                        help_text="Data statistik untuk tahun ini",
                        upload_to="qgis_data/yearly/",
                        verbose_name="Upload File Data CSV Tahun Ini",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Preview gambar untuk ditampilkan di grid card",
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="Thumbnail Peta",
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(
                        blank=True,
                        help_text="Deskripsi singkat tentang data tahun ini",
                        verbose_name="Deskripsi Singkat",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Centang untuk menampilkan peta ini",
                        verbose_name="Aktif",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_maps",
                        to="frontend.homepage",
                        verbose_name="Halaman Utama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peta Per Tahun",
                "verbose_name_plural": "Peta Per Tahun",
                "ordering": ["-tahun"],
            },
        ),
    ]
