# Generated by Django 5.2.8 on 2025-11-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_yearlymap"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yearlymap",
            options={
                "ordering": ["tahun"],
                "verbose_name": "Peta Per Tahun",
                "verbose_name_plural": "Peta Per Tahun",
            },
        ),
        migrations.RemoveField(
            model_name="yearlymap",
            name="deskripsi",
        ),
        migrations.RemoveField(
            model_name="yearlymap",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="yearlymap",
            name="data_csv",
            field=models.FileField(
                blank=True,
                help_text="Data statistik untuk tahun ini",
                null=True,
                upload_to="qgis_data/yearly/",
                verbose_name="Upload File Data CSV Tahun Ini",
            ),
        ),
    ]
