# Generated by Django 5.2.8 on 2025-11-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "frontend",
            "0003_alter_yearlymap_options_remove_yearlymap_deskripsi_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="data_csv",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="url_peta",
        ),
    ]
